'use strict';
/**
 * Generates ready-to-paste Claude Code session prompts in Dave's standing
 * structure — the same shape every session this month has actually used:
 * Task 0 (front-loaded irreversible risk), Phase 0 state audit, an ordered
 * priority queue worked top-down, one commit per atomic task, a living
 * CHECKPOINT.md, and a graceful (not percentage-based) stop.
 *
 * Primary: bundles ranked candidates, in rank order, until cumulative
 * effortHours reaches the target (>= 50% of a 5-hour window, i.e. 2.5h).
 * Light alternate: zero-build-volume items only (the quick unlocks/manual
 * actions) — genuinely smaller, not just a shorter slice of the same list.
 */

const PRIMARY_TARGET_HOURS = 2.5; // 50% of a 5-hour window
const TODAY = () => new Date().toISOString().slice(0, 10);

function slugify(label) {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40);
}

/** Greedily bundles ranked candidates until targetHours is reached (or the list runs out). */
function buildSessionQueue(rankedCandidates, targetHours) {
  const items = [];
  let totalHours = 0;
  for (const c of rankedCandidates) {
    if (totalHours >= targetHours) break;
    items.push(c);
    totalHours += c.effortHours;
  }
  return { items, totalHours: parseFloat(totalHours.toFixed(2)) };
}

function lightAlternateQueue(rankedCandidates) {
  const items = rankedCandidates.filter(c => c.buildVolume === 0);
  const totalHours = parseFloat(items.reduce((sum, c) => sum + c.effortHours, 0).toFixed(2));
  return { items, totalHours };
}

function renderTaskList(items) {
  return items.map((c, i) => `${i + 1}. **${c.label}** (~${c.effortHours}h)\n   ${c.why}`).join('\n\n');
}

/**
 * renderSessionPrompt({ branchSlug, title, queue, isLight, rankingContext })
 * Returns a single paste-ready markdown string, no editing required to run.
 */
function renderSessionPrompt({ branchSlug, title, queue, isLight, generatedFor }) {
  const capacityLine = isLight
    ? `**Target usage:** light — a day with less available capacity. Estimated queue: ~${queue.totalHours}h.`
    : `**Target usage:** at least 50% of a 5-hour window (2.5h+). Estimated queue: ~${queue.totalHours}h.`;

  const task0 = queue.items[0] && queue.items[0].category === 'non_code_blocker'
    ? `## Task 0 — front-loaded irreversible/high-value risk\n\n${queue.items[0].label}\n\n${queue.items[0].why}\n\n`
    : '';
  const remainingItems = task0 ? queue.items.slice(1) : queue.items;

  return `# Claude Code session: ${title}

**Branch:** \`feature/${branchSlug}\` (off \`main\` — this repo has no \`master\` branch)
${capacityLine}
**Generated by:** Merlin, ${generatedFor}. Advisor-generated — review before running; Merlin recommends, it does not act.

---

## Session structure (standing rules)

- Ordered priority queue, worked top-down. No fixed task count — do as much as capacity allows.
- Atomic tasks, one commit per task. Never leave a mid-change state across a stop point.
- Living \`CHECKPOINT.md\`, updated after every task, so any stop is safe.
- Phase 0 state audit first: verify each queue item's premise is still true before starting it (repo state may have moved since this prompt was generated) — mark done/partial/not-started, skip what's already done.
- Graceful stop, not a percentage: when running low, finalize \`CHECKPOINT.md\` and stop cleanly rather than starting a task that can't be finished and committed.

---

${task0}## Priority queue

${renderTaskList(remainingItems)}

---

## Definition of done

- Phase 0 audit complete.
- Queue worked top-down as far as capacity allows; anything not reached rolls to the next session.
- Living \`CHECKPOINT.md\` present and current as of the last committed task.
- No emojis, sentence case, "AI agent" not "bot" in any customer-facing string touched.
`;
}

function buildSessionPrompts({ ranking, generatedFor }) {
  const primaryQueue = buildSessionQueue(ranking.ranked, PRIMARY_TARGET_HOURS);
  const lightQueue = lightAlternateQueue(ranking.ranked);

  const top = ranking.recommendation;
  const primaryTitle = top ? `${top.label}` : 'clear the priority queue';
  const primarySlug = top ? slugify(top.id || top.label) : 'priority-queue';

  const primary = renderSessionPrompt({
    branchSlug: primarySlug, title: primaryTitle, queue: primaryQueue, isLight: false, generatedFor,
  });
  const light = renderSessionPrompt({
    branchSlug: `${primarySlug}-quick-wins`, title: `${primaryTitle} — quick wins only`, queue: lightQueue, isLight: true, generatedFor,
  });

  return { primary, light, primaryQueue, lightQueue };
}

module.exports = { buildSessionQueue, lightAlternateQueue, renderSessionPrompt, buildSessionPrompts, PRIMARY_TARGET_HOURS, slugify };
